### ISSUE TITLE
Bad request: 400, random failure with message of "Sending.....

### ISSUE THREAD

**Issue by jkexbx** [thomst08/requestrr#2]
Randomly, some users are getting what appears to be a time out. Is there any more debugging I can enable?

On discord, requestrr just says "Sending....."

In the logs, it shows:

fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while searching movies with title the marvels : Bad request: 400
      DSharpPlus.Exceptions.BadRequestException: Bad request: 400
         at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.MovieSelection(String customId, MovieRequest request, IReadOnlyList`1 movies) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 46
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.ShowMovieSelection(MovieRequest request, IReadOnlyList`1 movies) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 31
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 49
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle0(InteractionContext ctx, String movieTitle)

**Comment by thomst08** [comment]
Hey @jkexbx,

This is a common issue I've seen on our Discord support server, from your logs, I can see your using an older version.  Recently I have taken over maintaining Requestrr, and as a consequent, all newer updates come from a new repo/location.

If you have installed Requestrr locally, you can get the newest update [here.](https://github.com/thomst08/requestrr/releases/latest)
If you are using docker, you will need to remove and setup the container again with your old settings, an example of these commands are:
```
sudo docker stop requestrr && sudo docker rm requestrr

sudo docker run \
  --name requestrr \
  -p 4545:4545 \
  -v path to config:/root/config \
  --restart unless-stopped \
  thomst08/requestrr:latest
```

If you are using Unraid, force an update, it should pull an update form the new location automatically, are worst, remove it and reinstall it.

I hope that helps, let me know if this works for you or if you have any issues.

**Comment by jkexbx** [comment]
Thanks for following up. I am using unraid, and did have to remove it and reinstall. It wouldn't pull an update just in unraid.

Funny enough, I get the exact same error when I rerun the search now that I'm on the new fork.

Error while searching movies with title marvels : Bad request: 400
      DSharpPlus.Exceptions.BadRequestException: Bad request: 400
         at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.MovieSelection(String customId, MovieRequest request, IReadOnlyList`1 movies) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 46
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.ShowMovieSelection(MovieRequest request, IReadOnlyList`1 movies) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 31
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 41
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle0(InteractionContext ctx, String movieTitle)

**Comment by thomst08** [comment]
Thank you, I have seen a couple of reports of this exact same issue this morning on our Discord server and have recreated the issue, I have located the issue and will get a fix made soon, I will keep you posted when I have resolved the issue.

**Comment by thomst08** [comment]
@jkexbx, I have created a new build to correct this bug.
https://github.com/thomst08/requestrr/releases/tag/V2.1.4-hf3

Please let me know if this is still an issue after updating.

**Comment by jkexbx** [comment]
Thanks! Confirmed running the new build. I'll keep an eye to see if it happens again.

Starting Requestrr - build v2.1.4 - Hotfix 3

**Comment by thomst08** [comment]
Excellent, I have reports from others having the same issue and they have reported everything is working fine after this update, I will keep this open for a few days and close it if this is no longer reported.

**Comment by thomst08** [comment]
There has been no more reports of this issue, I consider it to be resolved.
