### ISSUE TITLE
Having no tag for Radarr breaks requests

### ISSUE THREAD

**Issue by pkp24** [thomst08/requestrr#41]
I didn't have a tag and it failed, I created a new tag and added it. Now it works. I'm not sure how not having a tag causes a quality profile error.

> fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClient[0]
      An error while requesting movie "Pearl" from Radarr: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "QualityProfileId",
          "errorMessage": "\u0027Quality Profile Id\u0027 must be greater than \u00270\u0027.",
          "attemptedValue": -1,
          "severity": "error",
          "errorCode": "GreaterThanValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "comparisonValue": 0,
            "comparisonProperty": "",
            "propertyName": "Quality Profile Id",
            "propertyValue": -1
          }
        },
        {
          "propertyName": "QualityProfileId",
          "errorMessage": "Quality Profile does not exist",
          "attemptedValue": -1,
          "severity": "error",
          "errorCode": "QualityProfileExistsValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "propertyName": "Quality Profile Id",
            "propertyValue": -1
          }
        }
      ]
      System.Exception: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "QualityProfileId",
          "errorMessage": "\u0027Quality Profile Id\u0027 must be greater than \u00270\u0027.",
          "attemptedValue": -1,
          "severity": "error",
          "errorCode": "GreaterThanValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "comparisonValue": 0,
            "comparisonProperty": "",
            "propertyName": "Quality Profile Id",
            "propertyValue": -1
          }
        },
        {
          "propertyName": "QualityProfileId",
          "errorMessage": "Quality Profile does not exist",
          "attemptedValue": -1,
          "severity": "error",
          "errorCode": "QualityProfileExistsValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "propertyName": "Quality Profile Id",
            "propertyValue": -1
          }
        }
      ]
         at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.CreateMovieInRadarr(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 282
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 229
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while handling interaction: An error occurred while requesting a movie from Radarr
      System.Exception: An error occurred while requesting a movie from Radarr
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 243
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(Int32 theMovieDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 110
         at Requestrr.WebApi.RequestrrBot.ChatBot.HandleMovieRequestAsync(ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 426
         at Requestrr.WebApi.RequestrrBot.ChatBot.DiscordComponentInteractionCreatedHandler(DiscordClient client, ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 352
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.

**Comment by thomst08** [comment]
Hey,

Thanks for letting me know, that is a good pickup, I'll test it and look into it.
