### ISSUE TITLE
Radarr: Invalid Path

### ISSUE THREAD

**Issue by captn3m0** [thomst08/requestrr#43]
Requestrr works fine for a while, but ocassional requests to Radarr result in an empty path being sent as the Path/RootFolderPath in the request. This is the error on the Radarr side:

```
[Warn] RadarrErrorPipeline: Invalid request Validation failed:
 -- Path: Invalid Path: ''
 -- RootFolderPath: Invalid Path: ''
```

This is the log on the requestrr side:

```
      An error while requesting movie "REDACTED" from Radarr: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "Path",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": null,
            "propertyName": "Path",
            "propertyValue": null
          }
        },
        {
          "propertyName": "RootFolderPath",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "attemptedValue": "",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": "",
            "propertyName": "Root Folder Path",
            "propertyValue": ""
          }
        }
      ]
      System.Exception: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "Path",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": null,
            "propertyName": "Path",
            "propertyValue": null
          }
        },
        {
          "propertyName": "RootFolderPath",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "attemptedValue": "",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": "",
            "propertyName": "Root Folder Path",
            "propertyValue": ""
          }
        }
      ]
         at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.CreateMovieInRadarr(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 282
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 229
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while handling interaction: An error occurred while requesting a movie from Radarr
      System.Exception: An error occurred while requesting a movie from Radarr
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 243
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(Int32 theMovieDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 121
         at Requestrr.WebApi.RequestrrBot.ChatBot.HandleMovieRequestAsync(ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 429
         at Requestrr.WebApi.RequestrrBot.ChatBot.DiscordComponentInteractionCreatedHandler(DiscordClient client, ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 389
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClient[0]
      An error while requesting movie "REDACTED" from Radarr: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "Path",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": null,
            "propertyName": "Path",
            "propertyValue": null
          }
        },
        {
          "propertyName": "RootFolderPath",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "attemptedValue": "",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": "",
            "propertyName": "Root Folder Path",
            "propertyValue": ""
          }
        }
      ]
      System.Exception: RadarrMovieCreation failed: Bad Request - [
        {
          "propertyName": "Path",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": null,
            "propertyName": "Path",
            "propertyValue": null
          }
        },
        {
          "propertyName": "RootFolderPath",
          "errorMessage": "Invalid Path: \u0027\u0027",
          "attemptedValue": "",
          "severity": "error",
          "errorCode": "PathValidator",
          "formattedMessageArguments": [],
          "formattedMessagePlaceholderValues": {
            "path": "",
            "propertyName": "Root Folder Path",
            "propertyValue": ""
          }
        }
      ]
         at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.CreateMovieInRadarr(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 282
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 229
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while handling interaction: An error occurred while requesting a movie from Radarr
      System.Exception: An error occurred while requesting a movie from Radarr
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV3.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV3.cs:line 243
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(Int32 theMovieDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 121
         at Requestrr.WebApi.RequestrrBot.ChatBot.HandleMovieRequestAsync(ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 429
         at Requestrr.WebApi.RequestrrBot.ChatBot.DiscordComponentInteractionCreatedHandler(DiscordClient client, ComponentInteractionCreateEventArgs e) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 389
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClient[0]
      An error occurred while searching available movies with Radarr: RadarrGetAllMovies failed: Not Found -
      System.Exception: RadarrGetAllMovies failed: Not Found -
         at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV2.SearchAvailableMoviesAsync(HashSet`1 theMovieDbIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV2.cs:line 200
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      An error occurred while retrieving all movie notification: An error occurred while searching available movies with Radarr
      System.Exception: An error occurred while searching available movies with Radarr
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV2.SearchAvailableMoviesAsync(HashSet`1 theMovieDbIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV2.cs:line 229
         at Requestrr.WebApi.RequestrrBot.Notifications.Movies.MovieNotificationEngine.<Start>b__8_0() in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Notifications\Movies\MovieNotificationEngine.cs:line 44
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClient[0]
      An error occurred while searching for movies with Radarr: RadarrMovieLookup failed: Not Found -
      System.Exception: RadarrMovieLookup failed: Not Found -
         at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV2.SearchMovieAsync(MovieRequest request, String movieName) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV2.cs:line 175
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while searching movies with title natrang : An error occurred while searching for movies with Radarr
      System.Exception: An error occurred while searching for movies with Radarr
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClientV2.SearchMovieAsync(MovieRequest request, String movieName) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Radarr\RadarrClientV2.cs:line 187
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMoviesAsync(String movieName) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 79
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 49
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle778(InteractionContext ctx, String movieTitle)
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
```

The path is configured correctly on the requestrr side, and it works.

**Comment by thomst08** [comment]
Hey @captn3m0,

Thank you, I've seen this pop up on occasion, I'll add this to the fix to correct.
I'll keep you updated when I find a solution.

**Comment by Mazo** [comment]
Have been seeing this with Sonarr too. There is an issue raised here https://github.com/Ombi-app/Ombi/issues/5215

You would expect sonarr to use the default root folder if requestrr didn't pass one though
