### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by Jihalizad** [thomst08/requestrr#46]
To start off, any help that can be given is appreciated so thank you for your time in reading this!

So, I haven't used it in a while but last I knew it was working fine. I went and tried to use it today and I ended up getting this error, I've tried multiple times to request a movie but no dice.
Also, on the docker container when I double-check settings it says everything is fine when verifying settings, it can talk to Sonarr/Radarr supposedly, no file locations have changed, just app updates as always.

As for the log, here's what I'm getting...
Note: I've not even tried to make a Sonarr request, just a Radarr request;, that said both were working at last check without anything but app updates for changes

text  error  warn  system  array  login  

Starting Requestrr - build 'v2.1.6'
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {obscuring} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /root
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
**warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClient[0]
      An error occurred while searching available tv shows with Sonarr: Connection refused (192.168.1.2:8989)
      System.Net.Http.HttpRequestException: Connection refused (192.168.1.2:8989)
       ---> System.Net.Sockets.SocketException (111): Connection refused**
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV4.HttpGetAsync(HttpClient client, SonarrSettings settings, String url) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV4.cs:line 642
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV4.SearchSerieByTvDbIdAsync(Int32 tvDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV4.cs:line 482
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV4.FindSeriesInSonarrAsync(Int32 tvDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV4.cs:line 464
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV4.GetTvShowDetailsAsync(HashSet`1 theTvDbIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV4.cs:line 242
**warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.**

**Comment by thomst08** [comment]
Hey @Jihalizad,

Thanks for reaching out, happy to help.
Having a look at your logs, there is no indication of a Radarr request being made which is odd...

I can think of why you might be getting the Sonarr message, there's a chance you have something in your notification file, requestrr will be checking Sonarr for that and it seems to be unable to talk to Sonarr.
It might pay just to re-enter your Sonarr settings and try it again, but any updates like to a firewall might block the connection, but if its testing ok.... Then that is odd, double check the Sonarr version too.

The issue causing the communication issue between Sonarr and Requestrr might be related to Radarr, so let's start there first.

Let me know if you find an issues when you re-enter the settings, you can also reach me on the Discord server too.

**Comment by Jihalizad** [comment]
The gluetunvpn application that all the communication for my Radarr/Sonarr/Requestrr/Transmission/Jackett communicate through has updated multiple times since first install but so far they're all still working, just got two new files earlier tonight. 

Double-checked again and yeah both Movies and TV Shows shows "The specified settings are valid." when testing.
![image](https://github.com/user-attachments/assets/6b7eb834-f836-40c9-8c92-b0959fcb960a)
![image](https://github.com/user-attachments/assets/40867413-c8cb-4c86-a1d0-6890edee48ae)
![image](https://github.com/user-attachments/assets/bf403ce7-118f-4053-b55b-bb585e272ecd)
Calibre is stopped because I ended up not liking it, I like using AudioBookShelf better. Also when initially set up, Requestrr was already set to use container:GluetunVPN as its network connection and was working fine but this does make me curious if you think that may have done it, it's not firewall but, it is a possible connection break point and all.

**Comment by thomst08** [comment]
Everything looks OK, did you check/alter the "tv" category? Might be worth clicking edit and checking the settings there.

Hmmm, the vpn shouldn't be causing an issue unless it's blocking something, can you test it with a different network connection temporarily? Just to rule that out.

**Comment by Jihalizad** [comment]
No alterations have been done no, also very very interesting suggestion because if I remove the "--restart=unless-stopped --net=container:GluetunVPN" parameter, specifically the one forcing the use of gluetunvpn's connection, it can STILL verify to Radarr just fine with no settings changed, but not to Sonarr. I've tried putting the IP/Port/API Key back in and yep, nothing, just invalid host and/or port coming back when doing a Test Settings.

After changing the network back to "none" and adding the -net=container:GluetunVPN back in I'm able to once again test the connections and they both verify fine again.

**Comment by thomst08** [comment]
Hmmmm, your logs now don't seem to have Sonarr errors any more, so that's good.
Does the message "The application did not respond" come up straight after you enter the command? or does it return something else first?
I have seen this else where, you might find it will correct itself... Basically I've seen some issues where it does not respond and you get no errors on your logs, but after a day or two, the bot just starts working again, this could be an issue contacting Discords servers.

I'm sorry I can't offer more advice right now.
Keep an eye on your logs and let me know if anything weird happens

**Comment by Jihalizad** [comment]
The message comes after a short wait after entering the command, like it's reaching out and trying and then failing. Maybe it is Discord. So far I've no real idea as to why it would just suddenly fail since everything was working great earlier, no worries and thanks for the review and all I really appreciate the effort!

**Comment by Jihalizad** [comment]
Well, sure enough after a few more updates and then restarting Requestrr last, it looks to be working again. I've only made the one request so far but hey, so far so good!
