### ISSUE TITLE
Notifications are not being sent

### ISSUE THREAD

**Issue by thomst08** [thomst08/requestrr#56]
Notifications for some requests seem to be lost,
in this test a movie is requested through Overseerr to Radarr.

The recorded ID for a a movie in the notifications file is sent from Requestrr to TVDB, at the time of recording the ID it links and is found within the Overseerr DB, but when doing an auto search for the ID on TVDB, the ID isn't found, this seems to be because the ID is for Overseerr's DB and doesn't link directly.
This then in turn tells Requestrr this movie/show is no longer on the TVDB and is removed.

The correct ID needs to be recorded from Overseerr in this case or needs to search Overseerr first before TVDB.

Example error:
```
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient[0]
      An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
       ---> System.Net.Sockets.SocketException (104): Connection reset by peer
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.HttpGetAsync(HttpClient client, String apiKey, String url) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 1036
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.HttpGetAsync(HttpClient client, OverseerrSettings settings, String url) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 1022
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.SearchMovieAsync(MovieRequest request, Int32 theMovieDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 402
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient[0]
      An error occurred while getting availability for a specific movie with TMDB ID 1235499 from Overseer: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
      System.Exception: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.SearchMovieAsync(MovieRequest request, Int32 theMovieDbId) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 414
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.Requestrr.WebApi.RequestrrBot.Movies.IMovieSearcher.SearchAvailableMoviesAsync(HashSet`1 movieIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 214
fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient[0]
      An error occurred while searching for availables movies from Overseerr: An error occurred while getting availability for a specific movie with TMDB ID 1235499 from Overseer: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
      System.Exception: An error occurred while getting availability for a specific movie with TMDB ID 1235499 from Overseer: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.Requestrr.WebApi.RequestrrBot.Movies.IMovieSearcher.SearchAvailableMoviesAsync(HashSet`1 movieIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 224
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      An error occurred while retrieving all movie notification: An error occurred while searching for availables movies from Overseerr: An error occurred while getting availability for a specific movie with TMDB ID 1235499 from Overseer: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
      System.Exception: An error occurred while searching for availables movies from Overseerr: An error occurred while getting availability for a specific movie with TMDB ID 1235499 from Overseer: An error occurred while searching for a movie by tmdbId "1235499" from Overseerr: An error occurred while sending the request.
         at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.Requestrr.WebApi.RequestrrBot.Movies.IMovieSearcher.SearchAvailableMoviesAsync(HashSet`1 movieIds, CancellationToken token) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 233
         at Requestrr.WebApi.RequestrrBot.Notifications.Movies.MovieNotificationEngine.<Start>b__8_0() in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\Notifications\Movies\MovieNotificationEngine.cs:line 44
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Removing notifications for Movie 1235499
```

**Comment by thomst08** [comment]
TV shows seem to be having this issue more on the new seerr update (but could be a coincidence), restarting the connecting services also seems to cause the clearing of media in notification, this needs to be corrected
